extends Node

enum CARD_SUITS { CLUBS, DIAMONDS, SPADES, HEARTS }
enum CARD_VALUES { 
			TWO = 2, THREE = 3, FOUR = 4, FIVE = 5,
			SIX = 6, SEVEN = 7, EIGHT = 8, NINE = 9,
			TEN = 10, JACK = 11, QUEEN = 12, KING = 13,
			ACE = 14 }
enum STRENGTH { LOW, HIGH }

const CARD_NAMES = { 
			CARD_VALUES.TWO: "2",
			CARD_VALUES.THREE: "3",
			CARD_VALUES.FOUR: "4",
			CARD_VALUES.FIVE: "5",
			CARD_VALUES.SIX: "6",
			CARD_VALUES.SEVEN: "7",
			CARD_VALUES.EIGHT: "8",
			CARD_VALUES.NINE: "9",
			CARD_VALUES.TEN: "10",
			CARD_VALUES.JACK: "J",
			CARD_VALUES.QUEEN: "Q",
			CARD_VALUES.KING: "K",
			CARD_VALUES.ACE: "A" }
const CARD_STRENGHTS = {
			CARD_VALUES.TWO : STRENGTH.LOW,
			CARD_VALUES.THREE : STRENGTH.LOW,
			CARD_VALUES.FOUR : STRENGTH.LOW,
			CARD_VALUES.FIVE : STRENGTH.LOW,
			CARD_VALUES.SIX : STRENGTH.LOW,
			CARD_VALUES.SEVEN : STRENGTH.LOW,
			CARD_VALUES.EIGHT : STRENGTH.HIGH,
			CARD_VALUES.NINE : STRENGTH.HIGH,
			CARD_VALUES.TEN : STRENGTH.HIGH,
			CARD_VALUES.JACK : STRENGTH.HIGH,
			CARD_VALUES.QUEEN : STRENGTH.HIGH,
			CARD_VALUES.KING : STRENGTH.HIGH,
			CARD_VALUES.ACE : STRENGTH.HIGH}
